services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: playlistmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: playlistmanager
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/playlistmanager
      SPRING_DATASOURCE_USERNAME: kyungmin
      SPRING_DATASOURCE_PASSWORD: kyungmin2892

volumes:
  pgdata: